name: todo-api

services:

  nginx:
    image: docker.io/library/nginx:1.27.1
    ports:
      - 127.0.0.1:8443:8443
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/todo-api.local.key:/etc/nginx/ssl/todo-api.local.key:ro
      - ./docker/nginx/todo-api.local.crt:/etc/nginx/ssl/todo-api.local.crt:ro
    depends_on:
      todo-api:
        condition: service_healthy

  todo-api:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm-multistage
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://postgresql:5432/todo-api
      QUARKUS_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      QUARKUS_PROFILE: cookie
    ports:
      - 127.0.0.1:8081:8080
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/q/health/live"]
      interval: 3s
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    image: docker.io/bitnami/postgresql:14.13.0
    volumes:
      - bitnami:/bitnami/postgresql:rw
    environment:
      POSTGRESQL_DATABASE: todo-api
      POSTGRESQL_USERNAME: todo-api
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-U", "todo-api"]
      interval: 3s

volumes:
  bitnami: {}
